language: python
python:
- '2.7'
install:
- sudo apt-get install -y libssl-dev libffi-dev git python-pip python-virtualenv
- git clone http://git.openstack.org/openstack/tempest
- sudo pip install tempest/
before_script:
- virtualenv .venv
- source .venv/bin/activate
- pip install -U -r tempest/requirements.txt
- cp -f tests/tempest.conf etc/
- 'echo -e "- username: ${USER}\n  tenant_name: ${TENANT}\n  password: ${PASSWORD}" > etc/accounts.yaml'
- wget 'https://launchpadlibrarian.net/149320341/cirros-0.3.1-i386-disk.vmdk'
- testr init

script:
- testr run tempest.scenario.test_minimum_basic.TestMinimumBasicScenario --concurrency=1
notifications:
  email: false
env:
  global:
  - OS_TOP_LEVEL=./tempest/
  - OS_TEST_PATH=./tempest/tempest/test_discover
  - secure: "bZ97e5vohEvnMgHwKjAbw7hOsgUGkX9KY5DJBHCPIIpxQWKGcshxl4epEt1ktmnxJDRxeu/3iYRQACpKsZwOYZiYyQQDpCVmg8I6OfHwJMuopaZHv2U9SJtozzg8PKPhqyPh+7MYW1XYVnxGobrATnDG0Nq+avIjhMd1np2lLhcSf7AqHExx2ep7xhqiB0lhquNqahrF6W7qa7HTXvnwklKnlNSHejUeVIn17Pnb9exXAl0aKtH8wxPQuNlUcKfbXY0qSznD0zfID9QHjCKTUQ9RkAVbcoWka3pJBruVaW2SRI130XJ3e3xhj4KS0osv6Sb30zQgKoQ1Xg98Kt00hH7lZa3mfddILMooMG01D5SABnDhybIV6T4IYT4jLIxedIIr4qmzt0KSJ7MuVJ00ImGovy46ZMX+9+eFf3oVb9jvbbDWNg/ca1P271zhhb7XCMtjekfGfsQ01JnMO1WPacXsTyM1xmR+g61Qn/oSYWHBCUEYCvkt0NBhpGfTZLkSCivJ657vFw0rnTw9mkUP8gZlPciMG0Cf8O6M7vTe9Y+f1Dtg8Hh2+0Dxk8F2zCk0xsHzoWpNiIdMRh6ACh8QIvl4F5mzb3TDXo+ljOMbYhCnreQgb/AO5NYWgm2Y/JcFeXXg0ipHLZWCoGI6vASr1H+9p3h8Gr74bb7HJhyAqBE="
  - secure: "sjtkBETzkNzQGnDr1QiyRIAzAaFabQvVfqngjheNY5FnEFXqINRl2u8VH7LEUumEOWXjNCGKfrnpPddGznYX5i3CDZXagVoxbeD1sHJTAq4vmR2X/3/jpVoNWkPMJOc/yLtNlI4rpP+hgK2gingK3rhDNYwliGjoERvQlUlp+0f0Z+NeovVrrWliGCwjQcNM1JBYqKhEM+HsUW3MSyD+p1VmPT0H787F3TDl99SpDtITvqFf8ch+BM/UbfXcsSEtCS7OwbnW2Zvguw9oTJkfG7q4XD54niAIoZLXBtCDJ1EEKskodg3+qA/BgOv1Dy3P+VXdx3Wu2GrxcuDePIgyPdz8UGKRlVeC/hAQ9A5tF/kfKPTU+SXEGxFk6pWiQpWANh/VIrkGQDWl3pksJIRu3VRoxpeehdSJ5pyzaKu5Vz4YYq6oij48ASAbCq0KRLGuRwDCbSBEn00Ww9UwBvtU1JqAyAhe5g9bmXyHFBAM2X8GyH+XTuaInYrbxHN3dAXLYshA+OY9VC0bICtOaX1IcEq7eQiguvL0cloG82TORAjpM4lYiVc+/i53k77XaESALeirAV2R1SWmlNcrGR/O90v12BLxACG3WgogymuxPdyblMa5WKCsy0oGxdCrcPCMqp8CFzACmIJOT1xx+0qq/9t4Kd8HtaS0HIfm4QXEXzE="
  - secure: "A37hXUwEub1O1Pwy2yBVOtCS0ZnC0PCuYkmGOay5304H2ptQlLyUCdLLu2Yq+bEdF+r09KH6YbWAqYcxFd1dBVDsiJDryjnYzYaPsMz5stI7pDL2qNAulYdnp1XW8xRWWsKZuKj4kBXBTqfzjsxCnzSyCNKIKZuLve7fB8zsDV5HUili7ljFAcbwVJpUGuuyy4dDkSSvPK2AwZZhMFflW1iBLf2pGYU6SYWeLlqh0CWH17bPl3mrbbjP0++5G+ZoolrKqRajI7JYZQc8vmXqIyGcPeVb1rvcAeRfRD65UHbMPLKbv+2eOdOnHstCzClxyCC7qw/PBtrMfc9cFYH23kqyrMDCDii/ySXxF0vY/zYjlbKVuBAIno7dvTKzYUHZ1Wes5gQORbKVrCByenzTvsypmAEdXgkmHBd/pfkPNDQzrpw6BdCY6pqtuFLitsc1f1A650JMLXKKgIjrv7H4Gf9IcRiP2QKH5lqtSpm0xtuaj62lICIOlBtsQ2GfHF36Ihsa0dPVs2KShfFXdFNzGQnhQDRnyBKZD0zzn4sVVWMajQn6g+U3FBMJNymCZzE7w6P2eE8ngvNEd3r9S8vDQJvcf/HKBAkz+O4Mo5PPxMsSv0IkN+yQzyS27oJTrrpEdvGt9BxrFhBjKTnWXhT+9XR4TBihwgpfzSGQkvHM2J8="
