language: python
python:
- '2.7'
install:
- sudo apt-get install -y libssl-dev libffi-dev git python-pip python-virtualenv
- git clone http://git.openstack.org/openstack/tempest
- sudo pip install tempest/
before_script:
- virtualenv .venv
- source .venv/bin/activate
- pip install -U -r tempest/requirements.txt
- cp -f tests/tempest.conf etc/
- 'echo -e "- username: ${USER}\n  tenant_name: ${TENANT}\n  password: ${PASSWORD}"
  > etc/accounts.yaml'
- wget 'http://download.cirros-cloud.net/0.3.1/cirros-0.3.4-x86_64-uec.tar.gz'
- testr init
script:
- testr run tempest.scenario.test_minimum_basic.TestMinimumBasicScenario --concurrency=1
notifications:
  email: false
env:
  global:
  - OS_TOP_LEVEL=./tempest/
  - OS_TEST_PATH=./tempest/tempest/test_discover
  - secure: HzbTP0aF2k0uO6oEZZ7F8u8egrwVK4KFF0+mdhV6K/p+T2CfwHpOvp6YoTayMoTobs7spD+MEBnlYvlSbLJMTZwfrKQTMpvhMVQddf1zae8UV7Mto94PSTf4IWpcNh+HKyRTKFUuV7xFVgPrH2n5XZIAS4qUuN0vrhgCzlEJsNCCZIty+oui+dg10v3eG+/XCyxW8a8OINlQpe7gI8fCE7O4I2lNa2CKGwggtPVzprIOSj4wohM13g9bxE64DE3ZyZNOzvje3qD9fELV64HtMvavmmP8ckYvOWf5zPF27YvtdNCDAh2jn3xYuAYlaDm6b/M+OPmns6TtiQIHTtCkt7+DPD6tu2lZF3Zaj5DlsDBK7w9LTa8mESuvHB4YFR9heW9BhfYJ+nJ2qfdXxoBGRnr3WrjfHzEoXMzKKzf3D+0YyvDYfF9UCrFd+NvVfTxtW1UuwN3j7hxQfJsAwb5WeVpXPcxkoFci8tg6j1N6alDckFYd9pmcDktJmDqG/PMfDyTe6nZqLSQmpc5+q3UxUaZRw5oB6Tlu4lVyp1puv9ZfhERIwmT53gQFDX6ElsguEQeWfjZ6WdaBcqshqX9H3ofaJ945XHxz4GBk+JXBWkfJtGL7R8cKZhLLJtvPgv+Mjc5hZCqsJnmBl6jrSBslWmOzPhVBqn9OC0Xs0AJyG2E=
  - secure: BxhQ9ATkG4WM483SsKzZKVNJa4KjyK1o0vxKuK0g5+A4fEIvQh/GasMNPRovO4lMRNAjhqiH/aj8477GyxV8uKL9gXIX4Hps8pMDQgM3jm0RC6sVFI4TPlJxJbiuoP0E1F9jS9K5XlrerME2xYQwuxbO4JT7Mf/8GKdxQzTjqKawzcn7WUH63Jt50kzB815DAdavQdlrU/pNlXqt9bvX6UmgSmqcZdWTQaySD872Vy7fu37Axue8W46vMgdr52RU+rIqI0gIAy1cfM6yohA6sYeWMmGlvVIr81WeGOqV437A3MxvZXpXWmDfUwd4bMDMs4EuYkUqEeQzFLhUKBRhAtbbH4smMrTs1rehLBv05oY0LJaLZ5GUFcyer71a4GjYmuIV3OTUAVPHcUmkxTm5lsnRIPBXNdGVgkktyZygJyUdgv1zFkAU8+Q0UtLytIpV/h90kQpqBGGCwo5ogkMtpti1MFVCm/LEGiFRm+ilxK2twckLSxCIuYqvQv0YEn/9JEDXulb/ie8MUS7j58zCfSrTCI+izirh3oYDm3ZiLw/JsqTnUFR2lXzhIYRS8SaUftA/+hJm4qRotXYEs+6hf/JvOlSkae8+sdYZNPdymrD7lYZxM/KTNnp97um85YVUwVeztC3Vi5K0/l18LTYJUsE80+aAIqiVut6nOYPgQI8=
  - secure: RPqyyutaiB8tq8l2N3/MSqvcbp9fxjTc8ZYRJcZcWjfZP/HM32y8vHbscu+fMJs6uOTopIumFqg3KjNfGaBKlgDOnUY3jvX4qtEBXC4M0ZSEPgg2FcmLFYonwLEhTyoucGnM+5UDcn3Hi044f83cBxzjT7YQbjTg/ETrkg6TF9c0efaRFPVN+ZaRQBMqXeIgZbsLh869yYpjzBt/WDRk8b1SHQ8+Q9nWWjaGiuq+WxoJRS8iAXAMbv2WxTFZ9k58A2sDnKvN2/+e573nXV6eaJbGRuoPYUznLRT3pTfw5v7aO2EGkXi9eNxsVq6iT/qx+vq20Ia75MEYqRuCNPB/9cDR/xLNapiwVmg6JAFPM6XU8W1ciLmRfhdcRdoPnzcb0c0xzu7UVrzpDXE8xCKrrkfyYbYmOs2wVRi0dr5PcYPeBPckIB/JhgPa1FzjU0ItcKbt0yT06DCSPDVxA2rT6mV+nePsVQ/GH13AkUKB2baeqKpnf0mgCudbyRQxwIESDGX/YR5WEbt6wrb4ubbqOp6VcLd4M4tBqtmPLuwBk64P8NAvZ8AhFUT74O90cSyzrSTZo6qkbYpniuGIpkCIcI9p6LxZaXtUvQMuKF11Jh1Pq27qZSwujp37pD03CIgOQ0f6AyuODCo0jMoGKQQtKgRhiVk6L1Yksx4I/0vJkE0=
